services:
  _defaults:
    autowire: true
    autoconfigure: true
  
  FRZB\ServiceTemplate\:
    resource: '../src/**'
    exclude:
    - '../src/**/{Attribute,Util,Helper,Request,Response,Contract,ValueObject,Enum,DTO,Model,Message,Event,Data,Exception,UseCase,Tests}/**'
    - '../src/**/{*Kernel.php}'
